server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/automation_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000