server:
  port: 8084

spring:
  application:
    name: crop-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/crop_inventory_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    lk.ijse.gdse71.cropservice: DEBUG
    org.springframework.data.mongodb: DEBUG