server:
  port: 8082

spring:
  application:
    name: sensor-service

external:
  iot:
    base-url: http://104.211.95.241:8080/api
    username: "Visun"
    password: "123456"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000